const sellerProductsTypes = {
    
    SAVE_SELLER_PRODUCTS_START : 'SAVE_SELLER_PROUCTS_START',
    
    GET_SELLER_PRODUCTS_START: 'GET_SELLER_PRODUCTS_START',
    SET_SELLER_PRODUCTS:'SET_SELLER_PRODUCTS',
   
    GET_SELLER_PRODUCTS_DETAILS_START: 'GET_SELLER_PRODUCTS_DETAILS_START',
    SET_SELLER_PRODUCTS_DETAILS: 'SET_SELLER_PRODUCTS_DETAILS',


    DELETE_SELLER_PRODUCT_START: 'DELETE_SELLER_PRODUCT_START',
    UPDATE_SELLER_PRODUCT_START: 'UPDATE_SELLER_PRODUCT_START',

    GET_ALL_SELLER_PRODUCTS_START: 'GET_ALL_SELLER_PRODUCTS_START',

    FETCH_SELLER_PRODUCTS_START: 'FETCH_SELLER_PRODUCTS_START',


    
    
    
    
    
    // SAVE_ORDER_HISTORY_START: 'SAVE_ORDER_HISTORY_START',
    // GET_USER_ORDER_HISTORY_START: 'GET_USER_ORDER_HISTORY_START',
        // SET_USER_ORDER_HISOTRY: 'SET_USER_ORDER_HISOTRY',
    // GET_ORDER_DETAILS_START: 'GET_ORDER_DETAILS_START',
        // SET_ORDER_DETAILS: 'SET_ORDER_DETAILS',
    // GET_CUSTOMER_ORDERS_HISTORY_START: 'GET_CUSTOMER_ORDERS_HISTORY_START',



  };
  
  export default sellerProductsTypes